name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, latest]
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          node-gyp --version || true
          # npm config list -l
          npm install --global node-gyp
          node-gyp --version
          # npm config set node_gyp $(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js
          # npm config list -l
        shell: bash
      - run: npm install
        shell: bash
      - run: npm test
        shell: bash
      - run: node-gyp configure
        shell: bash
      - run: node-gyp rebuild
        shell: bash
  
