name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, latest]
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Not >= 3.12 because of distlib on node-gyp < 10.0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          node-gyp --version || true
          npm install --global node-gyp
          node-gyp --version
          npm install
          npm run
          npm test || true  # Why are there no tests?
        shell: bash
      - run: node-gyp configure
        shell: bash
      - run: node-gyp rebuild
        shell: bash
  
